# Generated by Django 5.0.2 on 2024-06-13 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QA_Block', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='slug',
        ),
    ]
