# Generated by Django 5.0.2 on 2024-03-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA_Block', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(default=models.CharField(max_length=200), help_text='Введите Вопрос', verbose_name='Вопрос'),
        ),
    ]
