# Generated by Django 5.0.2 on 2024-05-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA_Block', '0003_answer_answer_text_alter_question_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='updated',
        ),
        migrations.AlterField(
            model_name='answer',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
    ]
