# Generated by Django 5.0.2 on 2024-02-26 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthdate',
        ),
    ]
