# Generated by Django 5.0.2 on 2024-03-01 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
