# Generated by Django 5.0.2 on 2024-03-19 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0007_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='surname',
        ),
    ]
