# Generated by Django 5.0.2 on 2024-03-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0008_remove_user_name_remove_user_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='Введите фамилию', max_length=50, verbose_name='Фамилия'),
        ),
    ]
