# Generated by Django 5.0.2 on 2024-05-26 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0012_alter_user_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(help_text='Введите фамилию', max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(help_text='Введите имя', max_length=50, verbose_name='Имя')),
                ('middlename', models.CharField(help_text='Введите Отчество(если есть)', max_length=50, verbose_name='Отчество')),
                ('email', models.EmailField(help_text='Введите электронную почту', max_length=50, unique=True, verbose_name='Электронная почта')),
                ('sex', models.CharField(help_text='Введите Пол', max_length=1, verbose_name='Пол')),
                ('phone_number', models.CharField(help_text='Введите номер телефона', max_length=11, unique=True, verbose_name='Номер телефона')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
