# Generated by Django 5.0.2 on 2024-06-07 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0013_userprofile_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
