# Generated by Django 5.0.2 on 2024-06-07 14:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fi', models.CharField(verbose_name='Фамилия Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('phone_number', models.CharField(help_text='Введите номер телефона', max_length=11, unique=True, verbose_name='Номер телефона')),
                ('comment', models.CharField(verbose_name='Комментарий')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middlename', models.CharField(max_length=50, verbose_name='Отчество')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='Номер телефона')),
                ('sex', models.CharField(max_length=1, verbose_name='Пол')),
                ('main_photo', models.FileField(upload_to='media/photo/doctor', verbose_name='Главное фото')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название вакансии')),
                ('description', models.CharField(verbose_name='Описание')),
                ('salary', models.IntegerField(verbose_name='Зарплата')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('description', models.CharField(verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_eduaction_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='media/photo/doctor/education', verbose_name='Фото образования')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_photos', to='Oliva_pages.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='media/photo/doctor/files', verbose_name='Файлы статьей и т.д')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='Oliva_pages.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='media/photo/doctor/videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])], verbose_name='Видео')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='Oliva_pages.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='JobAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fi', models.CharField(verbose_name='Фамилия Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('phone_number', models.CharField(help_text='Введите номер телефона', max_length=11, unique=True, verbose_name='Номер телефона')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Oliva_pages.job')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='medical_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Oliva_pages.medicalservice'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Введите заголовок', verbose_name='Заголовок')),
                ('review_text', models.TextField(help_text='Введите свой отзыв', verbose_name='Отзыв')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Oliva_pages.doctor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
