# Generated by Django 5.0.2 on 2024-05-06 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oliva_pages', '0002_medical_service_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsreview',
            old_name='doctor',
            new_name='news',
        ),
        migrations.RemoveField(
            model_name='doctorreview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='medical_service_review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='newsreview',
            name='user',
        ),
        migrations.AddField(
            model_name='doctorreview',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Oliva_pages.review'),
        ),
        migrations.AddField(
            model_name='medical_service_review',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Oliva_pages.review'),
        ),
        migrations.AddField(
            model_name='newsreview',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Oliva_pages.review'),
        ),
    ]
