# Generated by Django 5.0.2 on 2024-06-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oliva_pages', '0002_alter_review_doctor_workschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='medical_service',
        ),
        migrations.AddField(
            model_name='doctor',
            name='spec',
            field=models.CharField(default=3, max_length=50, verbose_name='Специальность'),
            preserve_default=False,
        ),
    ]
