# Generated by Django 5.0.2 on 2024-05-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oliva_pages', '0003_rename_doctor_newsreview_news_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата события')),
                ('description', models.CharField(verbose_name='Описание события')),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.FileField(upload_to='files/news', verbose_name='Фото'),
        ),
    ]
