# Generated by Django 5.0.2 on 2024-05-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oliva_pages', '0004_calendarevents_alter_news_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='main_photo',
            field=models.FileField(upload_to='media/photo/doctor', verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.FileField(upload_to='media/photo/news', verbose_name='Фото'),
        ),
    ]
