# Generated by Django 5.0.2 on 2024-05-13 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oliva_pages', '0005_alter_doctor_main_photo_alter_news_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorShortcut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oliva_pages.doctor')),
            ],
        ),
    ]
