# Generated by Django 5.0.2 on 2024-05-13 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oliva_pages', '0006_doctorshortcut'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsShortcut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oliva_pages.news')),
            ],
        ),
    ]
