# Generated by Django 5.0.2 on 2024-05-21 08:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oliva_pages', '0007_newsshortcut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_eduaction_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='media/photo/doctor/education', verbose_name='Фото образования')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_photos', to='Oliva_pages.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='media/photo/doctor/files', verbose_name='Файлы статьей и т.д')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='Oliva_pages.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='media/photo/doctor/videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])], verbose_name='Видео')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='Oliva_pages.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен для записи')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedule', to='Oliva_pages.doctor')),
            ],
            options={
                'unique_together': {('doctor', 'date', 'start_time', 'end_time')},
            },
        ),
        migrations.DeleteModel(
            name='CalendarEvents',
        ),
        migrations.RemoveField(
            model_name='newsreview',
            name='news',
        ),
        migrations.RemoveField(
            model_name='newsshortcut',
            name='news',
        ),
        migrations.RemoveField(
            model_name='newsreview',
            name='review',
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DoctorShortcut',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='NewsShortcut',
        ),
        migrations.DeleteModel(
            name='NewsReview',
        ),
    ]
