# Generated by Django 5.0.2 on 2024-05-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oliva_pages', '0008_doctor_eduaction_photo_doctor_files_doctor_videos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название вакансии')),
                ('description', models.CharField(verbose_name='Описание')),
                ('salary', models.IntegerField(verbose_name='Зарплата')),
            ],
        ),
        migrations.AddField(
            model_name='medicalservice',
            name='price',
            field=models.IntegerField(default=3, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
